require: rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Include:
    - Rakefile
    - Guardfile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - bin/**/*
Metrics/LineLength:
  IgnoredPatterns: ['\A\s*#']
Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  ExcludedMethods:
    - guard
    - describe
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'
RSpec/MessageSpies:
  EnforcedStyle: receive
Style/Documentation:
  Enabled: false
RSpec/FilePath:
  Exclude:
    - 'spec/concepts/action/operation/challenge_spec.rb'
    - 'spec/concepts/action/operation/link_shared_spec.rb'
    - 'spec/concepts/action/operation/unknown_spec.rb'
    - 'spec/concepts/event/operation/handle_spec.rb'
    - 'spec/concepts/unfurl/operation/dispatch_spec.rb'
    - 'spec/concepts/unfurl/operation/github_spec.rb'
    - 'spec/concepts/unfurl/operation/pivotal_spec.rb'
