language: ruby
rvm: 2.4.2
bundler_args: --without production
env:
  global:
    - GITHUB_TOKEN=secret
    - GITHUB_USER=user
    - PIVOTAL_TOKEN=secret
    - SLACK_OAUTH_TOKEN=secret
    - SLACK_TOKEN=secret
before_script:
  - rake rubocop
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
