# frozen_string_literal: true

GITHUB_TOKEN = ENV.fetch('GITHUB_TOKEN')
GITHUB_USER = ENV.fetch('GITHUB_USER')
PIVOTAL_TOKEN = ENV.fetch('PIVOTAL_TOKEN')
SLACK_OAUTH_TOKEN = ENV.fetch('SLACK_OAUTH_TOKEN')
SLACK_TOKEN = ENV.fetch('SLACK_TOKEN')
