# frozen_string_literal: true

SLACK_TOKEN = ENV.fetch('SLACK_TOKEN')
SLACK_OAUTH_TOKEN = ENV.fetch('SLACK_OAUTH_TOKEN')
GITHUB_TOKEN = ENV.fetch('GITHUB_TOKEN')
PIVOTAL_TOKEN = ENV.fetch('PIVOTAL_TOKEN')
